name = "verification_module_ts"
main = "src/index.ts"
compatibility_date = "2023-02-16"


[env.staging]
[[kv_namespaces]]
binding = "VERIFICATION_TOKENS"
preview_id = "679bd5c734ac4707a687876b9439a249"
id = "679bd5c734ac4707a687876b9439a249"

NEPTUNE_ENV="dev"

TOKEN_EXP_TIME = "180"